# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-05 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180105_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='abstract',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u6458\u8981'),
        ),
        migrations.AlterField(
            model_name='blog',
            name=b'author',
            field=models.CharField(blank=True, max_length=16, verbose_name='\u4f5c\u8005'),
        ),
    ]
